config/routes.rb
Rails.application.routes.draw do
  resources :jawbones
  
  resources :users
  
  get 'auth_response' => 'auths#auth_response'

  root 'static#index' 
  
  get 'session/show' => 'session#show'  
  delete 'session/destroy' => 'session#destroy'
  match 'session', to: 'session#create', via: :post

end

app/models/jawbone.rb
class Jawbone < ActiveRecord::Base
  belongs_to :users  
  
  validates :user_xid, presence: true
  
  after_commit :alert
    
  def should_alert?
    events = Jawbone.where(:user_xid => self.user_xid, :responded => nil).order(:created_at).limit(3)
    return false if events.count < 3 or (events.last.created_at - events.first.created_at) > 60
    return true   
  end    
    
 
  def alert
   return unless should_alert?
   emergency_contact = self.e_num1
   band_owner = self.firstname + ' ' + self.lastname
   message = $client.account.messages.create(:to => emergency_contact, :from => $twilio_phone_number,                        
                                   :body => "Safe.me recognized an alert from #{band_owner}")
   if message
    puts "ALERT WAS TRIGGERD FOR ________#(band_owner}________"
    events = Jawbone.where(:user_xid => self.user_xid, :responded => nil).order(:timestamp).limit(3)  
    events.each  do |e| 
      e.responded = ture; 
      e.save 
    end
   end
  end
end

app/controllers/jawbones_controller.rb
class JawbonesController < ApplicationController
  http_basic_authenticate_with name: ENV["SAFEME_NAME"], password: ENV["SAFEME_SECRET"], except: :create
  before_action :validate, only:[:create]
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @jawbones = Jawbone.all
  end

  def show
  end

  def new
    @jawbone = Jawbone.new
  end

  def edit
  end

  def create            
    params[:events].each do |event|
      jawbone_params = {:user_xid => event['user_xid'],:action => event['action'],:data => params['events'].to_s,
      :timestamp => event['timestamp'].to_s, :jawbone_type => event['type']}
      @event = Jawbone.create(jawbone_params)
    end
    render :json => {:success => 200} 
  end

  def update
    respond_to do |format|
      if @jawbone.update(jawbone_params)
        format.html { redirect_to @jawbone, notice: 'Jawbone was successfully updated.' }
        format.json { render :show, status: :ok, location: @jawbone }
      else
        format.html { render :edit }
        format.json { render json: @jawbone.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @jawbone.destroy
    respond_to do |format|
      format.html { redirect_to jawbones_url, notice: 'Jawbone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_jawbone
      @jawbone = Jawbone.find(params[:id])
    end
    
    def validate
      render :json => {:status => 400} and return if params[:events].nil? or params[:secret_hash] != ENV['JAWBONE_SH']
    end
end

app/helpers/jawbones_helper.rb
module JawbonesHelper       
    
  def should_alert?(event)
    @events = Jawbone.where(:user_xid => event.user_xid, :responded => nil).order(:timestamp).limit(3)        
    return if @events.count < 3 
    return if (@events.last.timestamp - @events.first.timestamp) > 60
    return unless @events[0].action == 'enter_sleep_mode' or @events[0].action == 'exit_sleep_mode'
    return unless @events[1].action == 'exit_sleep_mode' or @events[1].action == 'enter_sleep_mode'
    return unless @events[2].action == 'exit_sleep_mode' or @events[2].action == 'enter_sleep_mode'
    
    alert = true
    if alert
      @events.each do |activity|
        e = activity
        e.responded = true
        e.save
      end
    end
  end
    
end

app/views/jawbones/_form.html.erb
<%= form_for(@jawbone) do |f| %>
  <% if @jawbone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jawbone.errors.count, "error") %> prohibited this jawbone from being saved:</h2>

      <ul>
      <% @jawbone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_xid %><br>
    <%= f.text_field :user_xid %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jawbones/edit.html.erb
<h1>Editing jawbone</h1>

<%= render 'form' %>

<%= link_to 'Show', @jawbone %> |
<%= link_to 'Back', jawbones_path %>

app/views/jawbones/index.html.erb
<h1>Listing jawbones</h1>

<table>
  <thead>
    <tr>
      <th>User xid</th>
      <th>Type</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jawbones.each do |jawbone| %>
      <tr>
        <td><%= jawbone.user_xid %></td>
        <td><%= jawbone.type %></td>
        <td><%= jawbone.action %></td>
        <td><%= link_to 'Show', jawbone %></td>
        <td><%= link_to 'Edit', edit_jawbone_path(jawbone) %></td>
        <td><%= link_to 'Destroy', jawbone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jawbone', new_jawbone_path %>

app/views/jawbones/new.html.erb
<h1>New jawbone</h1>

<%= render 'form' %>

<%= link_to 'Back', jawbones_path %>

app/views/jawbones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User xid:</strong>
  <%= @jawbone.user_xid %>
</p>

<p>
  <strong>Type:</strong>
  <%= @jawbone.type %>
</p>

<p>
  <strong>Action:</strong>
  <%= @jawbone.action %>
</p>

<%= link_to 'Edit', edit_jawbone_path(@jawbone) %> |
<%= link_to 'Back', jawbones_path %>