config/routes.rb
Rails.application.routes.draw do
  resources :jawbones
  
  resources :users
  
  get 'auth_response' => 'auths#auth_response'

  root 'static#index' 
  
  get 'session/show' => 'session#show'  
  delete 'session/destroy' => 'session#destroy'
  match 'session', to: 'session#create', via: :post

end

app/views/layouts/_about.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 text-center">
    <h2 class="section-heading">About Us</h2>
    <hr>
    <h4 >We're a group of Harvard, MIT, and Clark affiliates working on a 
     platform for using wearable devices to empower people to overcome the barriers to the 
     bystander intervention. For example, by allowing discrete signaling to friends that "this 
     person really IS bothering me." It extends the use of fitness bands as a safty alert system 
     that enable your Jawbone UP24 fitness tracker to send out a pre set text message to contacts. </h4>
    <div class='row'>
      <div class='col-md-6'><%=link_to image_tag('cf.png'), 'http://bit.ly/1fjf6vS', :target => '_blank'%></div>
      <div class='col-md-6'><%=link_to image_tag('bbj.png'), 'http://bit.ly/1JaqMZI', :target => '_blank'%></div>
    </div>
    <div class='row'>
      <div class='col-md-6'><%=link_to image_tag('mt.png'), 'http://bit.ly/1hgVk6a', :target => '_blank'%></div>
      <div class='col-md-6'><%=link_to image_tag('self.png'), 'http://on.self.com/1HQbb0c', :target => '_blank'%></div>
    </div>
  </div>
</div>

app/views/layouts/_alertprocess.html.erb
<section class="no-padding" id="portfolio">
        <div class="container-fluid">
          <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                  <a href="#" class="portfolio-box">
                      <%=image_tag "jawbone1.jpg", :class => "img-responsive"%>
                      <div class="portfolio-box-caption">
                          <div class="portfolio-box-caption-content">
                              <div class="project-category text-faded">
                                Step 1
                              </div>
                              <div class="project-name">
                                Enter Sleep Mode
                              </div>
                            </div>
                        </div>
                    </a>
                </div>
              <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                  <%=image_tag "jawbone2.jpg", :class => "img-responsive"%>
                  <div class="portfolio-box-caption">
                    <div class="portfolio-box-caption-content">
                      <div class="project-category text-faded">Step 2</div>
                              <div class="project-name">
                                  Exit Sleep Mode
                                </div>
                            </div>
                        </div>
                    </a>
              </div>
              <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%=image_tag "jawbone1.jpg", :class => "img-responsive"%>
                    <div class="portfolio-box-caption">
                    <div class="portfolio-box-caption-content">
                        <div class="project-category text-faded">Step 3</div>
                        <div class="project-name">Enter Sleep Mode</div>
                      </div>
                  </div>
                </a>
              </div>
            </div>
        </div>               
       </section>

app/views/layouts/_header.html.erb
<div class="header-content">
  <div class="header-content-inner">
    <h1>Alert your network with the simple press of your Jawbone fitness tracker</h1>
    <hr>
    <p>Winner of the 2014 Clinton Foundation Codeathon</p>
    <a href="#about" class="btn btn-xl page-scroll" style='color:white; border:2px solid white;'>Learn More</a>
    <%=link_to 'TRY IT', @url, :class => 'btn btn-xl btn-default page-scroll'%>
   
  
  </div>
</div>

app/views/layouts/_howitworks.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading">How It Works</h2><hr>
      <h4>SafeMe enable your UP24 band to work as a safty alert system. You can sign up to Safeme via 
      Jawbone and make sure to enter your phone and your emergency contact's phone. In case of an 
      threatening situation you can Enter and Exit from sleep mode in UP24 band with in one minute. PLEASE 
      NOTE: currently SafeMe is a beta product.</h4><br>
      <%=render 'layouts/alertprocess'%>
    </div>
  </div>
</div>

app/views/layouts/_meta_tags.html.erb
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Safeme fitness band safty alert system">
  <meta name="author" content="Dushyanthi Pieris">
  <title>Safeme</title>
 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

app/views/layouts/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="/" style='color:black;'>Safeme</a>
    </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <%unless session[:uid].present?%>
            <li><a class="page-scroll" href="#about">About</a></li>
            <li><a class="page-scroll" href="#howitworks">How it Works</a></li>
            <li><a class="page-scroll" href="#login">Login</a></li>
          <%else%>
            <li><%=link_to "Profile", user_path(session[:uid]), class: 'page-scroll'%></li>
            <li><%=link_to "Logout", session_destroy_path, method: :delete, class: 'page-scroll'%></li>
          <%end%>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%=render 'layouts/meta_tags'%>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <%=render 'layouts/navbar'%>
  <div class='container'>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-warning") %>
    <% end %>
    <br><br>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/website.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%=render 'layouts/meta_tags'%>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,600' rel='stylesheet' type='text/css'>
  <%=render 'layouts/shim'%>
</head>

<body id="page-top">
<%= yield %> 
</body>
</html>